plugins/redmine_status_history/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html



match 'projects/:project_id/issue_status_history/search' => 'status_histories#search', :via => [:get, :post], :as => 'search_status_history'
match 'projects/:project_id/issue_status_history/show_history/:issue_id' => 'status_histories#show_history', :via => [:get], :as => 'show_status_history'

plugins/redmine_status_history/app/models/issue_status_history.rb
class IssueStatusHistory < ActiveRecord::Base
  unloadable
  
  belongs_to :status, :class_name => 'IssueStatus', :foreign_key => 'status_id'
  belongs_to :user
  belongs_to :journal
  belongs_to :issue
  
  
  def self.search_changes(project, status_id, date_from, previous_status_id=nil, date_to=nil)

    conditions = {
      :from => date_from.to_date..(date_to.nil? ? Date.tomorrow : date_to.to_date.tomorrow)
    }

    if status_id.present?
      conditions[:status_id] = status_id
    end

    if previous_status_id.present?
      conditions[:previous_status_id] = previous_status_id 
    end
    
    Issue.
      where(:project_id => project.id).
      joins(:issue_status_histories).
      where({:issue_status_histories => conditions}).
      uniq
  end
end

plugins/redmine_status_history/app/controllers/status_histories_controller.rb
class StatusHistoriesController < ApplicationController
  unloadable
  
  before_action :find_project_by_project_id


  def index
    
  end

  def show_history
    @issue = Issue.find(params[:issue_id])
  end

  def search
    @statuses = @project.trackers.collect {|t| t.issue_statuses}.flatten.uniq.sort {|s, t| s.name <=> t.name}
    @status_to = params[:status_to]
    @status_from = params[:status_from]
    if params[:dates].present?
      @date_from = params[:dates][:date_from] 
      @date_to = params[:dates][:date_to]
    end
    
    @issues = []
    
    if request.post?
      @issues = IssueStatusHistory.search_changes(@project, @status_to, @date_from, @status_from, @date_to)
    end
    
  end
      
end

plugins/redmine_status_history/app/helpers/status_histories_helper.rb
module StatusHistoriesHelper
  
  def first_status(issue)
    issue.issue_status_histories.first.status if issue.issue_status_histories.any?
  end
  
  def issue_status_changes(issue)
    if issue.issue_status_histories.any?
      issue.issue_status_histories.drop(1)
    else
      []
    end
  end
end

plugins/redmine_status_history/app/views/hooks/_hook_link_to_status_history_search.html.erb
<p class="other-formats">
  <%= link_to l(:label_history_main_search), search_status_history_path(@project) if User.current.allowed_to?(:search_status_history, @project) %>
</p>

plugins/redmine_status_history/app/views/status_histories/_issue_status_history.erb
<h3 class="title"><%= issue %></h3>
<table class="list issues">
  <tbody>
    <tr>
      <td>
        <%=l(:label_history_issue_creation)%>
      </td>
      <td>
        <%= format_date(issue.created_on)%>
      </td>
      <td>
        <%= first_status(issue)%>
      </td>
      <td>
        <%= issue.author%>
      </td>
    </tr>
    <% issue_status_changes(issue).each do |c| %>
      <tr>
        <td></td>
        <td><%= format_date(c.from)%></td>
        <td><%= c.status%></td>
        <td><%= c.user%></td>
      </tr>
    <% end %>
  </tbody>
</table>

plugins/redmine_status_history/app/views/status_histories/_list_simple.html.erb
<% if issues && issues.any? %>
<%= form_tag({}) do %>
  <table class="list issues">
    <thead><tr>
    <th>#</th>
    <th><%=l(:field_tracker)%></th>
    <th><%=l(:field_subject)%></th>
    <th><%=l(:label_history_current_status)%></th>
    <th></th>
    
    </tr></thead>
    <tbody>
    <% for issue in issues %>
    <tr id="issue-<%= h(issue.id) %>" class="hascontextmenu <%= cycle('odd', 'even') %> <%= issue.css_classes %>">
      <td class="id">
        <%= link_to(issue.id, issue_path(issue)) %>
      </td>
      <td class="tracker"><%= issue.tracker %></td>
      <td class="subject">
        <%= link_to(issue.subject.truncate(60), issue_path(issue)) %>
      </td>
      <td>
        <%= issue.status %>
      </td>
      <td>
        <%= link_to l(:label_history_view_history), show_status_history_path(@project, issue), :remote => true %>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

plugins/redmine_status_history/app/views/status_histories/index.html.erb
<h2>StatusHistoriesController#index</h2>

plugins/redmine_status_history/app/views/status_histories/search.html.erb
<h2><%l(:label_history_main_search)%></h2>



<%= form_tag(search_status_history_path(@project)) do %>

<div class="tabular">
  <div class="splitcontent">
    <div class="splitcontentleft">
      <p>
        <label><%=l(:label_history_status_from)%></label>
        <%= select_tag 'status_from', options_from_collection_for_select(@statuses, "id", "name", @status_from) , :include_blank => true%>      
      </p>
      <p>
        <label><%=l(:label_history_date_from)%><span class="required"> *</span></label>
        <%= date_field(:dates, :date_from, {value:@date_from, :size => 10, :required => true}) %>
        <%= calendar_for('dates_date_from') %>          
      </p>
    </div>
    <div class="splitcontentright">
      <p>
        <label><%=l(:label_history_status_to)%></label>
        <%= select_tag 'status_to', options_from_collection_for_select(@statuses, "id", "name", @status_to) , :include_blank => true%>
        <%= calendar_for('status_from') %>
      </p>
      <p>
        <label><%=l(:label_history_date_to)%><span class="required"> *</span></label>
        <%= date_field(:dates, :date_to, {value: @date_to, :size => 10, :required => true}) %>
        <%= calendar_for('dates_date_to') %>
      </p>
    </div>

  </div>

</div>
<%= submit_tag l(:label_search)%>


<% end %>

<hr />
<!-- Issue list -->
<%= render :partial => 'list_simple', :locals => { :issues => @issues } %>
<% include_calendar_headers_tags %>

plugins/redmine_status_history/app/views/status_histories/show_history.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'issue_status_history', locals: {issue: @issue}) %>');
showModal('ajax-modal', '700px');
$('#ajax-modal').addClass('new-watcher');